### ISSUE TITLE
ObjectPointer does not exist any more?

### ISSUE THREAD

**Issue by szabgab** [StarrFox/memobj#5]
I tried to run the code from the README, but it seem ObjectPointer does not exist any more.

**Comment by StarrFox** [comment]
Sorry about that! I forgot to update the readme to the latest api

**Comment by szabgab** [comment]
np, I wrote a test with a few days ago, but did not have time to send the PR and now it failed.

**Comment by StarrFox** [comment]
yea I had been watching your fork as you made the tests, using the python interpreter itself to test things was a really good idea

**Comment by StarrFox** [comment]
issue should be fixed in <https://github.com/StarrFox/memobj/commit/23349ff919b39bc182eaf20bc5084f16f0ff91cf>

**Comment by szabgab** [comment]
Thanks. I see I cannot continue now as the GA tests fail in your repo as well.

**Comment by StarrFox** [comment]
yes I'm still working on a way to fix that bug, it's a pretty tricky issue

**Comment by StarrFox** [comment]
@szabgab tests are working again!
